extend type Mutation {
  """
  ✨ Insert a single `Crew` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  crew_insert(
    """
    Data object to insert into the table.
    """
    data: Crew_Data!
  ): Crew_KeyOutput! @fdc_generated(from: "Crew", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Membership` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  membership_insert(
    """
    Data object to insert into the table.
    """
    data: Membership_Data!
  ): Membership_KeyOutput! @fdc_generated(from: "Membership", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Message` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insert(
    """
    Data object to insert into the table.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `Crew` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  crew_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Crew_Data!]!
  ): [Crew_KeyOutput!]! @fdc_generated(from: "Crew", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Membership` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  membership_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Membership_Data!]!
  ): [Membership_KeyOutput!]! @fdc_generated(from: "Membership", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Message` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  message_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `Crew` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Crew`.
  """
  crew_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Crew_Data!
  ): Crew_KeyOutput! @fdc_generated(from: "Crew", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Membership` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Membership`.
  """
  membership_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Membership_Data!
  ): Membership_KeyOutput! @fdc_generated(from: "Membership", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Message` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Message_Data!
  ): Message_KeyOutput! @fdc_generated(from: "Message", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `Crew` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Crew`.
  """
  crew_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Crew_Data!]!
  ): [Crew_KeyOutput!]! @fdc_generated(from: "Crew", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Membership` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Membership`.
  """
  membership_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Membership_Data!]!
  ): [Membership_KeyOutput!]! @fdc_generated(from: "Membership", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Message` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Message`.
  """
  message_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Message_Data!]!
  ): [Message_KeyOutput!]! @fdc_generated(from: "Message", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `Crew` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Crew` or `null` if not found.
  """
  crew_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Crew_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Crew_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Crew_Data!
  ): Crew_KeyOutput @fdc_generated(from: "Crew", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Membership` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Membership` or `null` if not found.
  """
  membership_update(
    """
    The key used to identify the object.
    """
    key: Membership_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Membership_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Membership_Data!
  ): Membership_KeyOutput @fdc_generated(from: "Membership", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Message` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Message` or `null` if not found.
  """
  message_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Message_Data!
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `Crew` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  crew_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Crew_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Crew_Data!
  ): Int! @fdc_generated(from: "Crew", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Membership` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  membership_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Membership_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Membership_Data!
  ): Int! @fdc_generated(from: "Membership", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Message` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  message_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Message_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Message_Data!
  ): Int! @fdc_generated(from: "Message", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `Crew` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  crew_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Crew_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Crew_FirstRow
  ): Crew_KeyOutput @fdc_generated(from: "Crew", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Membership` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  membership_delete(
    """
    The key used to identify the object.
    """
    key: Membership_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Membership_FirstRow
  ): Membership_KeyOutput @fdc_generated(from: "Membership", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Message` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  message_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Message_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Message_FirstRow
  ): Message_KeyOutput @fdc_generated(from: "Message", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `Crew` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  crew_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Crew_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Crew", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Membership` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  membership_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Membership_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Membership", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Message` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  message_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Message_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Message", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
