extend type Crew {
  """
  ✨ List `Membership` objects in a one-to-many relationship (where `Membership`.`crew` is this object).
  """
  memberships_on_crew(
    """
    Filter condition to narrow down the query results.
    """
    where: Membership_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Membership_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Membership_Having
  ): [Membership!]! @fdc_generated(from: "Membership.crew", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`crew` is this object).
  """
  messages_on_crew(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.crew", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `Membership` as the join table (a `Membership` object exists where its `crew` is this and its `user` is that).
  """
  users_via_Membership(
    """
    Filter condition to narrow down the query results.
    """
    where: Membership_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Membership_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Membership_Having
  ): [User!]! @fdc_generated(from: "Membership", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Crew", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Crew` table.
  """
  _count: Int! @fdc_generated(from: "Crew", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `avatarUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  avatarUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.avatarUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `createdById` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdById_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.createdById", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `isPublic` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isPublic_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.isPublic", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `maxMembers` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  maxMembers_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.maxMembers", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Crew` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Crew.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Sum the `maxMembers` field in the `Crew` table.
  """
  maxMembers_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Crew.maxMembers", purpose: QUERY_SUM)
  """
  ✨ Average the `maxMembers` field in the `Crew` table.
  """
  maxMembers_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Crew.maxMembers", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Crew` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Crew.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `maxMembers` field in the `Crew` table.
  """
  maxMembers_min: Int @fdc_generated(from: "Crew.maxMembers", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Crew` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Crew.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Crew` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Crew.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `maxMembers` field in the `Crew` table.
  """
  maxMembers_max: Int @fdc_generated(from: "Crew.maxMembers", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Crew` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Crew.updatedAt", purpose: QUERY_MAX)
}
extend type Membership {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Membership", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Membership` table.
  """
  _count: Int! @fdc_generated(from: "Membership", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `canInvite` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  canInvite_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.canInvite", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `canModerate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  canModerate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.canModerate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `crewId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  crewId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.crewId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `isActive` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isActive_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.isActive", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `joinedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  joinedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.joinedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Membership` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Membership.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `joinedAt` field in the `Membership` table.
  """
  joinedAt_min: Timestamp @fdc_generated(from: "Membership.joinedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `joinedAt` field in the `Membership` table.
  """
  joinedAt_max: Timestamp @fdc_generated(from: "Membership.joinedAt", purpose: QUERY_MAX)
}
extend type Message {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Message", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Message` table.
  """
  _count: Int! @fdc_generated(from: "Message", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `content` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  content_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.content", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `crewId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  crewId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.crewId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `editedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  editedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.editedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `fileName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.fileName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `fileSize` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileSize_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.fileSize", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `fileUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.fileUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `imageUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  imageUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.imageUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `isDeleted` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isDeleted_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.isDeleted", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `messageType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  messageType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.messageType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `replyToMessageId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  replyToMessageId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.replyToMessageId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `senderId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  senderId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.senderId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `sentAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  sentAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.sentAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `thumbnailUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  thumbnailUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.thumbnailUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Message` table where the `videoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  videoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Message.videoUrl", purpose: QUERY_COUNT)
  """
  ✨ Sum the `fileSize` field in the `Message` table.
  """
  fileSize_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Message.fileSize", purpose: QUERY_SUM)
  """
  ✨ Average the `fileSize` field in the `Message` table.
  """
  fileSize_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Message.fileSize", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `editedAt` field in the `Message` table.
  """
  editedAt_min: Timestamp @fdc_generated(from: "Message.editedAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `fileSize` field in the `Message` table.
  """
  fileSize_min: Int @fdc_generated(from: "Message.fileSize", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `sentAt` field in the `Message` table.
  """
  sentAt_min: Timestamp @fdc_generated(from: "Message.sentAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `editedAt` field in the `Message` table.
  """
  editedAt_max: Timestamp @fdc_generated(from: "Message.editedAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `fileSize` field in the `Message` table.
  """
  fileSize_max: Int @fdc_generated(from: "Message.fileSize", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `sentAt` field in the `Message` table.
  """
  sentAt_max: Timestamp @fdc_generated(from: "Message.sentAt", purpose: QUERY_MAX)
}
extend type User {
  """
  ✨ List `Crew` objects in a one-to-many relationship (where `Crew`.`createdBy` is this object).
  """
  crews_on_createdBy(
    """
    Filter condition to narrow down the query results.
    """
    where: Crew_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Crew_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Crew_Having
  ): [Crew!]! @fdc_generated(from: "Crew.createdBy", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Membership` objects in a one-to-many relationship (where `Membership`.`user` is this object).
  """
  memberships_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Membership_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Membership_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Membership_Having
  ): [Membership!]! @fdc_generated(from: "Membership.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Message` objects in a one-to-many relationship (where `Message`.`sender` is this object).
  """
  messages_on_sender(
    """
    Filter condition to narrow down the query results.
    """
    where: Message_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Message_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Message_Having
  ): [Message!]! @fdc_generated(from: "Message.sender", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Crew` objects using `Membership` as the join table (a `Membership` object exists where its `user` is this and its `crew` is that).
  """
  crews_via_Membership(
    """
    Filter condition to narrow down the query results.
    """
    where: Membership_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Membership_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Membership_Having
  ): [Crew!]! @fdc_generated(from: "Membership", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `bio` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bio_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.bio", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `firebaseUID` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  firebaseUID_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.firebaseUID", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `isOnline` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isOnline_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.isOnline", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `lastActiveAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastActiveAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.lastActiveAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `profilePictureUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  profilePictureUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.profilePictureUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastActiveAt` field in the `User` table.
  """
  lastActiveAt_min: Timestamp @fdc_generated(from: "User.lastActiveAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastActiveAt` field in the `User` table.
  """
  lastActiveAt_max: Timestamp @fdc_generated(from: "User.lastActiveAt", purpose: QUERY_MAX)
}
